name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          stable: true

      - name: Build
        run: go build -o hyliota -v .
      - name: Run tests
        run: go test -v -race ./...

      - uses: actions/upload-artifact@v2
        with:
          name: hyliota
          path: hyliota